/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    permissions: Permission;
    roles: Role;
    categories: Category;
    locations: Location;
    events: Event;
    tickets: Ticket;
    notifications: Notification;
    'finance-settings': FinanceSetting;
    'payment-connections': PaymentConnection;
    promotions: Promotion;
    'email-template-defaults': EmailTemplateDefault;
    'organization-email-templates': OrganizationEmailTemplate;
    posts: Post;
    comments: Comment;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    permissions: PermissionsSelect<false> | PermissionsSelect<true>;
    roles: RolesSelect<false> | RolesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    locations: LocationsSelect<false> | LocationsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    tickets: TicketsSelect<false> | TicketsSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    'finance-settings': FinanceSettingsSelect<false> | FinanceSettingsSelect<true>;
    'payment-connections': PaymentConnectionsSelect<false> | PaymentConnectionsSelect<true>;
    promotions: PromotionsSelect<false> | PromotionsSelect<true>;
    'email-template-defaults': EmailTemplateDefaultsSelect<false> | EmailTemplateDefaultsSelect<true>;
    'organization-email-templates': OrganizationEmailTemplatesSelect<false> | OrganizationEmailTemplatesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    comments: CommentsSelect<false> | CommentsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role?: (number | null) | Role;
  roleName?: string | null;
  isOnboarded?: boolean | null;
  /**
   * Preferred location for event recommendations
   */
  defaultLocation?: (number | null) | Location;
  /**
   * Categories the user is interested in
   */
  preferredCategories?: (number | Category)[] | null;
  onboardingStep?: number | null;
  /**
   * Mark this user as an Event Organizer (EO)
   */
  isOrganizer?: boolean | null;
  avatar?: (number | null) | Media;
  /**
   * Short description shown on the organizer profile page
   */
  bio?: string | null;
  website?: string | null;
  instagram?: string | null;
  followersCount?: number | null;
  /**
   * Events the user has bookmarked/saved
   */
  likedEvents?: (number | Event)[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles".
 */
export interface Role {
  id: number;
  name: string;
  permissions?: (number | Permission)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "permissions".
 */
export interface Permission {
  id: number;
  name: string;
  key: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: number;
  name: string;
  code?: string | null;
  /**
   * Used to group locations on the onboarding picker
   */
  region?: ('sumatera' | 'jawa' | 'bali-nusra' | 'kalimantan' | 'sulawesi' | 'maluku-papua') | null;
  /**
   * Show this location at the top of the picker
   */
  featured?: boolean | null;
  /**
   * Optional emoji shown next to the name (e.g., 🌋, 🏝️)
   */
  emoji?: string | null;
  /**
   * Image shown on the Top Destinations card
   */
  coverImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * Nama icon (misal: Music, Coffee, etc.)
   */
  icon?: string | null;
  group:
    | 'school-activities'
    | 'hobbies'
    | 'home-lifestyle'
    | 'fashion'
    | 'government'
    | 'family-education'
    | 'spirituality'
    | 'charity-causes'
    | 'travel-outdoor'
    | 'science-tech'
    | 'health'
    | 'sports-fitness'
    | 'film-media'
    | 'arts'
    | 'community'
    | 'food-drink'
    | 'business'
    | 'music';
  status?: ('active' | 'inactive') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  /**
   * Short event summary shown in cards and editor previews
   */
  summary?: string | null;
  /**
   * URL-friendly identifier (auto-generated if left blank)
   */
  slug?: string | null;
  /**
   * Supports the HTML produced by the description editor
   */
  description?: string | null;
  coverImage?: (number | null) | Media;
  /**
   * Wide banner shown at the top of the event detail page
   */
  bannerImage?: (number | null) | Media;
  /**
   * Additional photos shown in the event gallery section
   */
  galleryImages?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * The user account that owns this event
   */
  organizer: number | User;
  status: 'draft' | 'published' | 'cancelled' | 'completed';
  startDate: string;
  endDate?: string | null;
  location?: (number | null) | Location;
  venue?: string | null;
  address?: string | null;
  isOnline?: boolean | null;
  isFree?: boolean | null;
  price?: string | null;
  category?: (number | null) | Category;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  interestedCount?: number | null;
  capacity?: number | null;
  /**
   * Define the ticket tiers for this event. Attendees will see these options when purchasing.
   */
  ticketTypes?:
    | {
        /**
         * e.g., General Admission, VIP, VVIP Table
         */
        name: string;
        /**
         * Brief description shown to attendees
         */
        description?: string | null;
        /**
         * Price in USD. Set to 0 for free tickets.
         */
        price: number;
        /**
         * Choose whether ticket sales stop on a date or when sold out
         */
        salesEndMode?: ('limited' | 'unlimited') | null;
        currency?: 'USD' | null;
        /**
         * Total number of tickets available for this tier
         */
        quantity: number;
        /**
         * Number of tickets already sold (auto-updated)
         */
        sold?: number | null;
        /**
         * Maximum tickets a single buyer can purchase
         */
        maxPerOrder?: number | null;
        /**
         * List of benefits included with this ticket
         */
        perks?:
          | {
              perk: string;
              id?: string | null;
            }[]
          | null;
        /**
         * When this ticket goes on sale (optional)
         */
        salesStart?: string | null;
        /**
         * When sales close for this ticket (optional)
         */
        salesEnd?: string | null;
        /**
         * Hide this ticket from public view
         */
        isHidden?: boolean | null;
        /**
         * Lower numbers appear first
         */
        sortOrder?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tickets".
 */
export interface Ticket {
  id: number;
  event: number | Event;
  order: string;
  purchaserName: string;
  purchaserEmail: string;
  purchaserPhone?: string | null;
  ticketType: string;
  price: number;
  status: 'active' | 'pending' | 'completed' | 'checked_in' | 'cancelled' | 'refunded';
  qrToken?: string | null;
  stripeCheckoutSessionId?: string | null;
  stripePaymentIntentId?: string | null;
  stripeDestinationAccountId?: string | null;
  paidAt?: string | null;
  checkedInAt?: string | null;
  checkedInBy?: (number | null) | User;
  paymentProvider?: ('stripe' | 'paypal') | null;
  serviceFeeAmount?: number | null;
  taxAmount?: number | null;
  subtotalAmount?: number | null;
  totalAmount?: number | null;
  currency?: 'USD' | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: number;
  recipient: number | User;
  type: 'order' | 'checkin' | 'finance' | 'system';
  title: string;
  message: string;
  link?: string | null;
  isRead?: boolean | null;
  readAt?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "finance-settings".
 */
export interface FinanceSetting {
  id: number;
  organizer: number | User;
  serviceFeePercent: number;
  taxPercent: number;
  taxLabel?: string | null;
  defaultProvider: 'auto' | 'stripe';
  /**
   * Checkout currency is locked to USD
   */
  currency: 'USD';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment-connections".
 */
export interface PaymentConnection {
  id: number;
  organizer: number | User;
  provider: 'stripe' | 'paypal';
  status: 'pending' | 'connected' | 'revoked' | 'disabled';
  /**
   * Used as the default checkout provider when multiple connections are active
   */
  defaultProvider?: boolean | null;
  /**
   * Stripe account id or PayPal merchant id
   */
  externalAccountId?: string | null;
  accountEmail?: string | null;
  accountName?: string | null;
  country?: string | null;
  /**
   * Provider capabilities and onboarding metadata
   */
  capabilities?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  authState?: string | null;
  accessToken?: string | null;
  refreshToken?: string | null;
  expiresAt?: string | null;
  connectedAt?: string | null;
  revokedAt?: string | null;
  onboardingUrl?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promotions".
 */
export interface Promotion {
  id: number;
  name: string;
  /**
   * Auto-generated from the name and used in URLs
   */
  slug?: string | null;
  /**
   * Code attendees enter at checkout
   */
  code?: string | null;
  type: 'code' | 'access';
  discountType: 'percent' | 'flat';
  discountValue: number;
  usageCount?: number | null;
  /**
   * Leave empty for unlimited usage
   */
  usageLimit?: number | null;
  scopeType: 'all' | 'events';
  /**
   * Shown only when the scope is set to specific events
   */
  events?: (number | Event)[] | null;
  status: 'draft' | 'active' | 'scheduled' | 'ended';
  startsAtMode: 'now' | 'custom';
  startsAt?: string | null;
  endsAtMode: 'sales_end' | 'custom';
  endsAt?: string | null;
  organizer: number | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-template-defaults".
 */
export interface EmailTemplateDefault {
  id: number;
  /**
   * Stable system key used to resolve the template in app flows
   */
  key: string;
  name: string;
  description?: string | null;
  status: 'active' | 'draft';
  subject: string;
  preheader: string;
  headline: string;
  body: string;
  ctaLabel: string;
  ctaUrl: string;
  campaignName: string;
  fromName: string;
  fromEmail: string;
  replyToEmail: string;
  organizationName: string;
  address: string;
  city: string;
  province: string;
  postalCode: string;
  country: string;
  brandColor: string;
  secondaryColor: string;
  backgroundColor: string;
  cardBackground: string;
  bodyTextColor: string;
  headingColor: string;
  footerTextColor: string;
  buttonTextColor: string;
  fontFamily: string;
  borderRadius: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organization-email-templates".
 */
export interface OrganizationEmailTemplate {
  id: number;
  organizer: number | User;
  defaultTemplate?: (number | null) | EmailTemplateDefault;
  key: string;
  organizerTemplateKey?: string | null;
  name: string;
  description?: string | null;
  status: 'active' | 'draft';
  subject: string;
  preheader: string;
  headline: string;
  body: string;
  ctaLabel: string;
  ctaUrl: string;
  campaignName: string;
  fromName: string;
  fromEmail: string;
  replyToEmail: string;
  organizationName: string;
  address: string;
  city: string;
  province: string;
  postalCode: string;
  country: string;
  brandColor: string;
  secondaryColor: string;
  backgroundColor: string;
  cardBackground: string;
  bodyTextColor: string;
  headingColor: string;
  footerTextColor: string;
  buttonTextColor: string;
  fontFamily: string;
  borderRadius: number;
  isCustomized?: boolean | null;
  customizedAt?: string | null;
  lastSyncedFromDefaultAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  author: number | User;
  content: string;
  image?: (number | null) | Media;
  /**
   * External link to include with the post (e.g., event registration page)
   */
  link?: string | null;
  /**
   * Display text for the link
   */
  linkTitle?: string | null;
  likesCount?: number | null;
  commentsCount?: number | null;
  likedBy?:
    | {
        user: number | User;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments".
 */
export interface Comment {
  id: number;
  post: number | Post;
  author: number | User;
  content: string;
  /**
   * Users tagged in this comment
   */
  mentions?:
    | {
        user: number | User;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'permissions';
        value: number | Permission;
      } | null)
    | ({
        relationTo: 'roles';
        value: number | Role;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'locations';
        value: number | Location;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'tickets';
        value: number | Ticket;
      } | null)
    | ({
        relationTo: 'notifications';
        value: number | Notification;
      } | null)
    | ({
        relationTo: 'finance-settings';
        value: number | FinanceSetting;
      } | null)
    | ({
        relationTo: 'payment-connections';
        value: number | PaymentConnection;
      } | null)
    | ({
        relationTo: 'promotions';
        value: number | Promotion;
      } | null)
    | ({
        relationTo: 'email-template-defaults';
        value: number | EmailTemplateDefault;
      } | null)
    | ({
        relationTo: 'organization-email-templates';
        value: number | OrganizationEmailTemplate;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'comments';
        value: number | Comment;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  roleName?: T;
  isOnboarded?: T;
  defaultLocation?: T;
  preferredCategories?: T;
  onboardingStep?: T;
  isOrganizer?: T;
  avatar?: T;
  bio?: T;
  website?: T;
  instagram?: T;
  followersCount?: T;
  likedEvents?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "permissions_select".
 */
export interface PermissionsSelect<T extends boolean = true> {
  name?: T;
  key?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles_select".
 */
export interface RolesSelect<T extends boolean = true> {
  name?: T;
  permissions?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  icon?: T;
  group?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  name?: T;
  code?: T;
  region?: T;
  featured?: T;
  emoji?: T;
  coverImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  summary?: T;
  slug?: T;
  description?: T;
  coverImage?: T;
  bannerImage?: T;
  galleryImages?:
    | T
    | {
        image?: T;
        id?: T;
      };
  organizer?: T;
  status?: T;
  startDate?: T;
  endDate?: T;
  location?: T;
  venue?: T;
  address?: T;
  isOnline?: T;
  isFree?: T;
  price?: T;
  category?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  interestedCount?: T;
  capacity?: T;
  ticketTypes?:
    | T
    | {
        name?: T;
        description?: T;
        price?: T;
        salesEndMode?: T;
        currency?: T;
        quantity?: T;
        sold?: T;
        maxPerOrder?: T;
        perks?:
          | T
          | {
              perk?: T;
              id?: T;
            };
        salesStart?: T;
        salesEnd?: T;
        isHidden?: T;
        sortOrder?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tickets_select".
 */
export interface TicketsSelect<T extends boolean = true> {
  event?: T;
  order?: T;
  purchaserName?: T;
  purchaserEmail?: T;
  purchaserPhone?: T;
  ticketType?: T;
  price?: T;
  status?: T;
  qrToken?: T;
  stripeCheckoutSessionId?: T;
  stripePaymentIntentId?: T;
  stripeDestinationAccountId?: T;
  paidAt?: T;
  checkedInAt?: T;
  checkedInBy?: T;
  paymentProvider?: T;
  serviceFeeAmount?: T;
  taxAmount?: T;
  subtotalAmount?: T;
  totalAmount?: T;
  currency?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  recipient?: T;
  type?: T;
  title?: T;
  message?: T;
  link?: T;
  isRead?: T;
  readAt?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "finance-settings_select".
 */
export interface FinanceSettingsSelect<T extends boolean = true> {
  organizer?: T;
  serviceFeePercent?: T;
  taxPercent?: T;
  taxLabel?: T;
  defaultProvider?: T;
  currency?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment-connections_select".
 */
export interface PaymentConnectionsSelect<T extends boolean = true> {
  organizer?: T;
  provider?: T;
  status?: T;
  defaultProvider?: T;
  externalAccountId?: T;
  accountEmail?: T;
  accountName?: T;
  country?: T;
  capabilities?: T;
  authState?: T;
  accessToken?: T;
  refreshToken?: T;
  expiresAt?: T;
  connectedAt?: T;
  revokedAt?: T;
  onboardingUrl?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promotions_select".
 */
export interface PromotionsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  code?: T;
  type?: T;
  discountType?: T;
  discountValue?: T;
  usageCount?: T;
  usageLimit?: T;
  scopeType?: T;
  events?: T;
  status?: T;
  startsAtMode?: T;
  startsAt?: T;
  endsAtMode?: T;
  endsAt?: T;
  organizer?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-template-defaults_select".
 */
export interface EmailTemplateDefaultsSelect<T extends boolean = true> {
  key?: T;
  name?: T;
  description?: T;
  status?: T;
  subject?: T;
  preheader?: T;
  headline?: T;
  body?: T;
  ctaLabel?: T;
  ctaUrl?: T;
  campaignName?: T;
  fromName?: T;
  fromEmail?: T;
  replyToEmail?: T;
  organizationName?: T;
  address?: T;
  city?: T;
  province?: T;
  postalCode?: T;
  country?: T;
  brandColor?: T;
  secondaryColor?: T;
  backgroundColor?: T;
  cardBackground?: T;
  bodyTextColor?: T;
  headingColor?: T;
  footerTextColor?: T;
  buttonTextColor?: T;
  fontFamily?: T;
  borderRadius?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organization-email-templates_select".
 */
export interface OrganizationEmailTemplatesSelect<T extends boolean = true> {
  organizer?: T;
  defaultTemplate?: T;
  key?: T;
  organizerTemplateKey?: T;
  name?: T;
  description?: T;
  status?: T;
  subject?: T;
  preheader?: T;
  headline?: T;
  body?: T;
  ctaLabel?: T;
  ctaUrl?: T;
  campaignName?: T;
  fromName?: T;
  fromEmail?: T;
  replyToEmail?: T;
  organizationName?: T;
  address?: T;
  city?: T;
  province?: T;
  postalCode?: T;
  country?: T;
  brandColor?: T;
  secondaryColor?: T;
  backgroundColor?: T;
  cardBackground?: T;
  bodyTextColor?: T;
  headingColor?: T;
  footerTextColor?: T;
  buttonTextColor?: T;
  fontFamily?: T;
  borderRadius?: T;
  isCustomized?: T;
  customizedAt?: T;
  lastSyncedFromDefaultAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  author?: T;
  content?: T;
  image?: T;
  link?: T;
  linkTitle?: T;
  likesCount?: T;
  commentsCount?: T;
  likedBy?:
    | T
    | {
        user?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments_select".
 */
export interface CommentsSelect<T extends boolean = true> {
  post?: T;
  author?: T;
  content?: T;
  mentions?:
    | T
    | {
        user?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}